# Generated by Django 5.1.4 on 2025-01-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efficiency_parameter_female',
            name='doc',
        ),
        migrations.AlterField(
            model_name='disposal_culling',
            name='revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disposal_culling',
            name='weight_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_female',
            name='sexual_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_female',
            name='weaning_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_female',
            name='weight_eight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_female',
            name='weight_six',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='sexual_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weaning_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_eight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_six',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifetime_litter_character',
            name='litter_weight_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifetime_litter_character',
            name='weight_weaning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_record_female',
            name='litter_weight_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_record_female',
            name='weaning_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_record_male',
            name='litter_weight_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service_record_male',
            name='weaning_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
