# Generated by Django 5.1.4 on 2024-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficiency_parameter_female',
            name='conform_at_eight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='conform_at_eight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
