# Generated by Django 5.1.4 on 2025-01-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigdata', '0002_remove_efficiency_parameter_female_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weaning_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
