# Generated by Django 5.1.4 on 2025-01-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigdata', '0003_alter_efficiency_parameter_male_weaning_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficiency_parameter_female',
            name='dow',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='conform_at_eight',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='doc',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='dos',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='dosm',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='litter_size_weaning',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='sexual_maturity_weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weaning_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weaning_weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_eight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_six',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
