# Generated by Django 5.1.4 on 2025-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigdata', '0004_alter_efficiency_parameter_female_dow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='litter_size_weaning',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='sexual_maturity_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weaning_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_eight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_six',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
