# Generated by Django 5.1.4 on 2025-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigdata', '0005_alter_efficiency_parameter_male_litter_size_weaning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_female',
            name='dow',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='conform_at_eight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='doc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='dos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='dosm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='litter_size_weaning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='sexual_maturity_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weaning_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_eight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efficiency_parameter_male',
            name='weight_six',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
